### PR TITLE
Imp scheduler

### PR DESCRIPTION
**Pull request by Lamonkey**
1. Used scheduler for scheduling job to run in the background
2. For now it used a fake stream.

### CODE REVIEW

**Comment by david12white** [comment]
Could you provide documentation/comments for this code? I'm not familiar with celery and don't understand the intention behind a lot of these changes. Also, what are the binary files for? And should we be committing settings.json?

**Comment by Lamonkey** [comment]
Currently, I'm not using celery. The reason I have those files is that they can be migrated to celery in the future. Currently, I'm using a simple backend scheduler. For the documentation, I think I have documented functions in views.py and tasks.py which explained the scheduler.  Do you want me to add more documentation for now?

**Comment by Lamonkey** [comment]
Oh and for the setting.json. Sorry didn't mean to push that. I will add that into gitignore in the future

**Comment by david12white** [comment]
I'm still having difficulty understanding the intention. Could you rename stuff like "fetch_result" and "send_result" to describe exactly what they're doing? And add documentation about what the cache is used for? The individual methods have decent documentation but I have no idea what the new structure of the system looks like.

**Comment by Lamonkey** [comment]
Are you talking about the method in views.py? I think I have documented those.

**Pull request merged**
